run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - gofmt
    - revive
    - staticcheck
    - gosimple
    - gosec

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
